name: github_codespaces_flutter_web
description: A sample Flutter web application.
version: 1.0.0
homepage: https://github.com/DanTup/github-codespaces-flutter-web
author: Danny Tuppeny <danny@tuppeny.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
